BC-6676 - Use v3 config
hpi-schul-cloud/tldraw-client pull request #67
Opened 2024-03-22 08:16 UTC by bischofmax

# Description

## Links to Tickets or other pull requests

## Changes

## Datasecurity

## Deployment

## New Repos, NPM pakages or vendor scripts

## Screenshots of UI changes

## Approval for review

- [x] All points were discussed with the ticket creator, support-team or product owner. The code upholds all quality guidelines from the PR-template.

> Notice: Please remove the WIP label if the PR is ready to review, otherwise nobody will review it.

2024-03-22 12:23 UTC, SevenWaysDP reviewed
Because of the comment in the code, Cedric should take a look at it

2024-03-25 07:17 UTC, CeEv requested changes

2024-03-25 07:17 UTC, CeEv commented on src/types/index.ts
> +export * from './Envs';
Eine empty line zum Schluss fehlt überall wo das "Durchfahrt verboten Schild" bei gitHub auftaucht.

2024-03-25 12:10 UTC, CeEv approved these changes

2024-03-26 07:50 UTC, CeEv approved these changes

2024-03-26 09:29 UTC, merged